### ISSUE TITLE
Sonnerie as embedded library

### ISSUE THREAD

**Issue by theronic** [njaard/sonnerie#3]
I would like to embed Sonnerie inside my application, but I'm not sure if that's easy to do. The tests seem to spin up an external sonnerie process?

**Comment by njaard** [comment]
It's not really easy to do directly, mostly because I haven't wanted to be bound to an API that could do that. Also, Sonnerie requires a number of background threads and I feel that's a bit heavy weight behavior to hide behind a library api.

With that said, I don't think it's extremely hard to spin up a process and connect to it via a unix domain socket just as (some of) the tests do. Some of the tests also use the unexported api and do operate in-process.

**Comment by njaard** [comment]
Your issue is valid and I would hope to expose a public API one day, but I'm just not ready for that commitment right now.

**Comment by njaard** [comment]
It took a while, but sonnerie was rewritten and now publishes a poorly-documented preliminary public API.
